name: Jest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change to src directory
      run: cd src
    - name: Install dependencies
      run: npm install
      working-directory: ./src
    - name: Start development server
      run: npm run dev
      working-directory: ./src
    - name: Run Jest Tests
      run: npm test
      working-directory: ./src
